#!/bin/bash

# အရောင်လေးတွေသတ်မှတ်ခြင်း
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Welcome Message
clear
echo -e "${CYAN}*************************************************${NC}"
echo -e "${CYAN}*                                               *${NC}"
echo -e "${GREEN}* Welcome to Aung Kyaw's Script                 *${NC}"
echo -e "${GREEN}* Created by Aung Kyaw                          *${NC}"
echo -e "${CYAN}*                                               *${NC}"
echo -e "${CYAN}*************************************************${NC}"
echo ""

# ၁။ လိုအပ်သော အချက်အလက်များ တောင်းခံခြင်း
read -p "Nginx နှင့် SSL အတွက် အသုံးပြုမည့် Sub Domain (ဥပမာ - vpn.yourdomain.com) ကို ရိုက်ထည့်ပါ: " DOMAIN_NAME
read -p "CloudFront WebSocket အတွက် သုံးမည့် Path (ဥပမာ - /ws-path) ကို ရိုက်ထည့်ပါ: " WS_PATH
read -p "Marzban တွင် WebSocket အတွက် သတ်မှတ်မည့် Xray Internal Port (ဥပမာ - 2082) ကို ရိုက်ထည့်ပါ: " WS_PORT

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၁။ Docker ကို Install လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
curl -fsSL https://get.docker.com | sh

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၂။ Marzban ကို Install လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၃။ Marzban Admin အကောင့် ဖန်တီးနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
marzban cli admin create --sudo
echo -e "${GREEN}Admin အကောင့် (aktech) အား အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။${NC}"

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၄။ Public & Private Key များကို .env ထဲသို့ ထည့်သွင်းနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"

KEYS=$(docker exec -i marzban-marzban-1 xray x25519)
PRIVATE_KEY=$(echo "$KEYS" | grep "Private key:" | awk '{print $3}')
PUBLIC_KEY=$(echo "$KEYS" | grep "Public key:" | awk '{print $3}')

echo -e "${CYAN}Private Key : $PRIVATE_KEY${NC}"
echo -e "${CYAN}Public Key  : $PUBLIC_KEY${NC}"

echo "" | sudo tee -a /opt/marzban/.env
echo "# Reality Keys Generated by Aung Kyaw's Script" | sudo tee -a /opt/marzban/.env
echo "REALITY_PRIVATE_KEY=$PRIVATE_KEY" | sudo tee -a /opt/marzban/.env
echo "REALITY_PUBLIC_KEY=$PUBLIC_KEY" | sudo tee -a /opt/marzban/.env

marzban restart
echo -e "${GREEN}Keys များကို /opt/marzban/.env ထဲသို့ အောင်မြင်စွာ ထည့်သွင်းပြီးပါပြီ။${NC}"

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၅။ Nginx နှင့် SSL (Certbot) ကို Install လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo apt update && sudo apt install nginx certbot python3-certbot-nginx -y

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၆။ Nginx Configuration (WS Proxy အပါအဝင်) ထည့်သွင်းနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo rm -f /etc/nginx/sites-available/marzban
sudo rm -f /etc/nginx/sites-enabled/marzban

# Config အသစ်ရေးထည့်ခြင်း (Dashboard နှင့် WebSocket နှစ်ခုလုံးအတွက်)
sudo cat <<EOF > /etc/nginx/sites-available/marzban
server {
    listen 80;
    server_name $DOMAIN_NAME;

    # Marzban Dashboard နှင့် API အတွက်
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }

    # AWS CloudFront မှလာမည့် WebSocket Connection အတွက်
    location $WS_PATH {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:$WS_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/marzban /etc/nginx/sites-enabled/

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၇။ Nginx Test လုပ်ပြီး SSL Certificate တောင်းခံနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo nginx -t
sudo systemctl restart nginx

sudo certbot --nginx -d $DOMAIN_NAME --non-interactive --agree-tos -m admin@$DOMAIN_NAME

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၈။ docker-compose.yml သို့ SSL Volume ထည့်သွင်းနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
COMPOSE_FILE="/opt/marzban/docker-compose.yml"

if ! grep -q "/etc/letsencrypt:/etc/letsencrypt:ro" "$COMPOSE_FILE"; then
    sudo sed -i '/volumes:/a\      - /etc/letsencrypt:/etc/letsencrypt:ro' "$COMPOSE_FILE"
    echo -e "${GREEN}SSL Volume path ကို ထည့်သွင်းပြီးပါပြီ။${NC}"
else
    echo -e "${CYAN}SSL Volume path သည် ရှိနှင့်ပြီးသား ဖြစ်ပါသည်။${NC}"
fi

marzban restart

echo -e "\n${CYAN}*************************************************${NC}"
echo -e "${GREEN}🎉 အားလုံးပြီးစီးပါပြီ!${NC}"
echo -e "${YELLOW}👉 Dashboard : https://$DOMAIN_NAME${NC}"
echo -e "${YELLOW}👉 WS Path   : $WS_PATH${NC}"
echo -e "${YELLOW}👉 WS Port   : $WS_PORT (Marzban Dashboard တွင် Inbound ဆောက်ရန်)${NC}"
echo -e "${CYAN}*************************************************${NC}\n"
