#!/bin/bash

# အရောင်လေးတွေသတ်မှတ်ခြင်း
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Welcome Message
clear
echo -e "${CYAN}*************************************************${NC}"
echo -e "${CYAN}* *${NC}"
echo -e "${GREEN}* Welcome to Aung Kyaw's Script            *${NC}"
echo -e "${GREEN}* Created by Aung Kyaw                     *${NC}"
echo -e "${CYAN}* *${NC}"
echo -e "${CYAN}*************************************************${NC}"
echo ""

# ၁။ Subdomain ကို အရင်မေးပါမယ်
read -p "Nginx နှင့် SSL အတွက် အသုံးပြုမည့် Sub Domain (ဥပမာ - vpn.yourdomain.com) ကို ရိုက်ထည့်ပါ: " DOMAIN_NAME

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၁။ Docker ကို Install လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
curl -fsSL https://get.docker.com | sh

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၂။ Marzban ကို Install လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၃။ Marzban Admin အကောင့် ဖန်တီးနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"

marzban cli admin create --sudo
echo -e "${GREEN}Admin အကောင့် (aktech) အား အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။${NC}"

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၄။ Public & Private Key များကို .env ထဲသို့ ထည့်သွင်းနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"

# Script အတွင်း Run ရန် -i ကိုသာ အသုံးပြုထားသည်
KEYS=$(docker exec -i marzban-marzban-1 xray x25519)
PRIVATE_KEY=$(echo "$KEYS" | grep "Private key:" | awk '{print $3}')
PUBLIC_KEY=$(echo "$KEYS" | grep "Public key:" | awk '{print $3}')

# Terminal တွင် မြင်ရအောင် ပြသခြင်း
echo -e "${CYAN}Private Key : $PRIVATE_KEY${NC}"
echo -e "${CYAN}Public Key  : $PUBLIC_KEY${NC}"

# /opt/marzban/.env ဖိုင်ထဲသို့ အလိုအလျောက် ထည့်သွင်းခြင်း
echo "" | sudo tee -a /opt/marzban/.env
echo "# Reality Keys Generated by Aung Kyaw's Script" | sudo tee -a /opt/marzban/.env
echo "REALITY_PRIVATE_KEY=$PRIVATE_KEY" | sudo tee -a /opt/marzban/.env
echo "REALITY_PUBLIC_KEY=$PUBLIC_KEY" | sudo tee -a /opt/marzban/.env

# .env အသစ်ဝင်သွားစေရန် Marzban ကို Restart ချပေးခြင်း
marzban restart
echo -e "${GREEN}Keys များကို /opt/marzban/.env ထဲသို့ အောင်မြင်စွာ ထည့်သွင်းပြီးပါပြီ။${NC}"

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၅။ Nginx နှင့် SSL (Certbot) ကို Install လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo apt update && sudo apt install nginx certbot python3-certbot-nginx -y

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၆။ Nginx Configuration ကို ထည့်သွင်းနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
# အဟောင်းရှိရင် ဖျက်ပါမယ်
sudo rm -f /etc/nginx/sites-available/marzban
sudo rm -f /etc/nginx/sites-enabled/marzban

# Config အသစ်ရေးထည့်ခြင်း (HTTPS အတွက် Port 80 ကိုအရင်ဖွင့်ပေးရပါမည်၊ Certbot မှ Auto ပြောင်းပေးသွားပါမည်)
sudo cat <<EOF > /etc/nginx/sites-available/marzban
server {
    listen 80;
    server_name $DOMAIN_NAME;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}
EOF

# Symlink ပြန်ချိတ်ခြင်း
sudo ln -s /etc/nginx/sites-available/marzban /etc/nginx/sites-enabled/

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၇။ Nginx ကို Test လုပ်ပြီး SSL Certificate တောင်းခံနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo nginx -t
sudo systemctl restart nginx

# SSL ကို လူကိုယ်တိုင် ဝင်မရိုက်ရဘဲ Auto အသက်သွင်းခြင်း
sudo certbot --nginx -d $DOMAIN_NAME --non-interactive --agree-tos -m admin@$DOMAIN_NAME


echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၈။ docker-compose.yml သို့ SSL Volume ထည့်သွင်းနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
COMPOSE_FILE="/opt/marzban/docker-compose.yml"

# File ထဲမှာ အဆိုပါစာကြောင်း ပါ/မပါ အရင်စစ်ဆေးပါမည် (Script ခဏခဏ run ရင် နှစ်ကြောင်းထပ်မဖြစ်အောင်ပါ)
if ! grep -q "/etc/letsencrypt:/etc/letsencrypt:ro" "$COMPOSE_FILE"; then
    # 'volumes:' ဆိုတဲ့ စာကြောင်းရဲ့အောက်မှာ 6 spaces ခြားပြီး Auto ရေးထည့်ပါမည်
    sudo sed -i '/volumes:/a\      - /etc/letsencrypt:/etc/letsencrypt:ro' "$COMPOSE_FILE"
    echo -e "${GREEN}SSL Volume path ကို docker-compose.yml တွင် အောင်မြင်စွာ ထည့်သွင်းပြီးပါပြီ။${NC}"
else
    echo -e "${CYAN}SSL Volume path သည် docker-compose.yml တွင် ရှိနှင့်ပြီးသား ဖြစ်ပါသည်။${NC}"
fi

# Volume အသစ် ချိတ်ဆက်မှု အသက်ဝင်စေရန် Marzban အား Restart ပြုလုပ်ခြင်း
marzban restart

echo -e "\n${CYAN}*************************************************${NC}"
echo -e "${GREEN}🎉 အားလုံးပြီးစီးပါပြီ! Aung Kyaw ရဲ့ Marzban ကို လုံခြုံရေးအပြည့်ဖြင့် အသုံးပြုနိုင်ပါပြီ။${NC}"
echo -e "${YELLOW}👉 URL      : https://$DOMAIN_NAME${NC}"
echo -e "${GREEN}👤 Username : aktech${NC}"
echo -e "${GREEN}🔑 Password : aktech${NC}"
echo -e "${CYAN}*************************************************${NC}\n"
