#!/bin/bash

# အရောင်လေးတွေသတ်မှတ်ခြင်း
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Welcome Message
clear
echo -e "${CYAN}*************************************************${NC}"
echo -e "${CYAN}*                                                 *${NC}"
echo -e "${GREEN}*   Welcome to Aung Kyaw's Node Setup Script      *${NC}"
echo -e "${GREEN}*   Optimized for Laravel & Cloudflare System     *${NC}"
echo -e "${CYAN}*                                                 *${NC}"
echo -e "${CYAN}*************************************************${NC}"
echo ""

# ဆာဗာ၏ IP ကို Auto ယူပါမည်
SERVER_IP=$(curl -s http://checkip.amazonaws.com)

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၁။ Docker ကို Install လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
curl -fsSL https://get.docker.com | sh

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၂။ Marzban ကို Install လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၃။ Uvicorn Port ကို 8001 သို့ ပြောင်းလဲနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
echo "" | sudo tee -a /opt/marzban/.env
echo "# Port Changed to 8001 for Nginx Reverse Proxy" | sudo tee -a /opt/marzban/.env
echo "UVICORN_PORT=8001" | sudo tee -a /opt/marzban/.env

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၄။ Nginx ကို Install နှင့် Config လုပ်နေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"
sudo apt update
sudo apt install nginx -y

# Nginx Config ရေးသွင်းခြင်း (Variables များ မပျက်စေရန် EOF အသုံးပြုထားသည်)
cat <<EOF | sudo tee /etc/nginx/sites-available/marzban
server {
    listen 8000;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # WebSocket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF

sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/marzban /etc/nginx/sites-enabled/
sudo nginx -t
sudo systemctl restart nginx

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၅။ Reality Public & Private Key များကို ထည့်သွင်းနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"

# Keys ထုတ်ရန် Marzban Container ကို အရင် Up လုပ်ရပါမည်
marzban restart
sleep 5 # Container တက်လာရန် ခဏစောင့်ပါ

KEYS=$(docker exec -i marzban-marzban-1 xray x25519)
PRIVATE_KEY=$(echo "$KEYS" | grep "Private key:" | awk '{print $3}')
PUBLIC_KEY=$(echo "$KEYS" | grep "Public key:" | awk '{print $3}')

# Terminal တွင် မြင်ရအောင် ပြသခြင်း
echo -e "${CYAN}Private Key : $PRIVATE_KEY${NC}"
echo -e "${CYAN}Public Key  : $PUBLIC_KEY${NC}"

# /opt/marzban/.env ဖိုင်ထဲသို့ အလိုအလျောက် ထည့်သွင်းခြင်း
echo "" | sudo tee -a /opt/marzban/.env
echo "# Reality Keys Generated by Aung Kyaw's Script" | sudo tee -a /opt/marzban/.env
echo "REALITY_PRIVATE_KEY=$PRIVATE_KEY" | sudo tee -a /opt/marzban/.env
echo "REALITY_PUBLIC_KEY=$PUBLIC_KEY" | sudo tee -a /opt/marzban/.env

echo -e "\n${YELLOW}==========================================${NC}"
echo -e "${GREEN}၆။ Marzban Admin အကောင့် ဖန်တီးနေပါသည်...${NC}"
echo -e "${YELLOW}==========================================${NC}"

# Admin အကောင့်ဖန်တီးခြင်း (--username နှင့် --password ဖြင့် အလိုအလျောက် ထည့်သွင်းခြင်း)
marzban cli admin create --sudo --username aktech --password aktech
echo -e "${GREEN}Admin အကောင့် (aktech) အား အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။${NC}"

# .env အသစ်ဝင်သွားစေရန် Marzban ကို နောက်ဆုံးအကြိမ် Restart ချပေးခြင်း
marzban restart
echo -e "${GREEN}Keys များကို /opt/marzban/.env ထဲသို့ အောင်မြင်စွာ ထည့်သွင်းပြီးပါပြီ။${NC}"

echo -e "\n${CYAN}*************************************************${NC}"
echo -e "${GREEN}🎉 အားလုံးပြီးစီးပါပြီ! Node ဆာဗာ အသင့်ဖြစ်နေပါပြီ။${NC}"
echo -e "${YELLOW}👉 Marzban Panel : http://${SERVER_IP}:8000${NC}"
echo -e "${GREEN}👤 Username      : aktech${NC}"
echo -e "${GREEN}🔑 Password      : aktech${NC}"
echo -e "${CYAN}*************************************************${NC}"
echo -e "${YELLOW}မှတ်ချက် - ဤ Node အား Laravel Panel တွင် ချိတ်ဆက်ရန် အထက်ပါ IP နှင့် Port ကို အသုံးပြုပါ။${NC}\n"
